image:
  file: .gitpod.dockerfile
ports:
  - port: 8000
tasks:
  - init: mysql -u root -e "create database bookstack" && 
          cp .env.example .env && 
          cp docker/nginx.conf /etc/nginx/nginx.conf && 
          cp docker/php-fpm.conf /etc/php/7.4/fpm/php-fpm.conf && 
          sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env && 
          sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env && 
          sed -i "s/DB_USERNAME=bookstack/DB_USERNAME=root/g" .env && 
          sed -i "s/DB_PASSWORD=bookstack/DB_PASSWORD=/g" .env && 
          composer install && 
          chmod -R 777  public/uploads storage/ bootstrap/cache/ && 
          npm install -y && 
          php artisan key:generate &&
          php artisan migrate --seed && 
          php artisan serve
  - name: Git ShortCut
    command: >
      git config --global alias.co checkout && git config --global alias.br branch && git config --global alias.ci commit &&  git config --global alias.st status
# image:
#   file: .gitpod.dockerfile
# ports:
# - port: 8000
#   onOpen: notify
# - port: 5432
#   onOpen: ignore
# - port: 3306
#   onOpen: ignore
# tasks:
# - name: Init & Logs 
#   command: >
#     ( mysqld --skip-grant-tables & ) &&
#     sleep 3 &&
#     ( mysql -uroot -e "USE mysql; UPDATE user SET authentication_string=PASSWORD(\"123456\") WHERE user='root'; UPDATE user SET plugin=\"mysql_native_password\" WHERE user='root'; FLUSH PRIVILEGES;" );
#     mysqladmin -uroot shutdown;
#     killall mysqld;
#     ( mysqld & );
#     pg_start.sh;
#     apachectl start;
#     clear;
#     multitail /var/log/apache2/access.log -I /var/log/apache2/error.log /var/log/mysql/mysql.log -I /var/log/mysql/error.log -I ~/pg/logs/pgsql.log;
# - name: Terminal
#   command: >
#     clear;
#     echo "Commands:";
#     echo " * apachectl start";
#     echo " * apachectl stop";
#     echo " * pg_start.sh";
#     echo " * pg_stop.sh";
#     echo " * mysqld &";
#     echo " * mysqladmin -uroot shutdown -p";
# - name: Git ShortCut
#   command: >
#     git config --global alias.co checkout && git config --global alias.br branch && git config --global alias.ci commit &&  git config --global alias.st status
# - name: Composer Install
#   command: >
#     composer install
# - name: Laravel setup
#   command: >
#     php artisan migrate:install
